name: CI

on:
  push:
    branches: [website]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install packages
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d main -u "github-actions-bot <support+actions@github.copm>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
